import { Inter } from "next/font/google";
import "./globals.css";
import favicon from '../app/favicon.ico'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SolveX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/x-icon" href="/images/favicon.ico"/>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
